name: Rebase command

on:
  issue_comment:
    types: [created]

jobs:
  rebase:
    name: Rebase
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      with:
        fetch-depth: 0

    - name: Automatic Rebase
      uses: cirrus-actions/rebase@c473b716e3fcde0c6bf67416e2c2882830ad40f6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
